[tools]
 python = "3.11" # [optional] will be used for the venv
uv = 'latest'
 [env]
 PROJECT_NAME = "{{ config_root | basename }}"
 _.python.venv = { path = "{{ config_root }}/.venv", create = true }
PYTHONPATH = "{{ config_root }}"

